const blocks=[
{id:'oportunidad',part:'Parte 1 - La oportunidad',title:'Que problema tiene el arquitecto hoy',summary:'El arquitecto pierde tiempo coordinando proveedores dispersos, cotizaciones lentas y fabricacion sin trazabilidad.',message:'El problema no es falta de diseno: es falta de sistema para convertir diseno en producto vendible, cotizable y entregable.',deliverable:'Diagnostico del dolor operativo y comercial',tools:['Lista de fricciones actuales','Mapa de tareas que no generan honorarios','Oportunidades de ingreso por mobiliario'],prompt:'Actua como consultor de negocio para un arquitecto interiorista. Diagnostica los problemas que tiene al vender mobiliario personalizado y conviertelos en una oportunidad comercial para crear una linea propia con respaldo productivo.'},
{id:'propuesta-enki',part:'Parte 1 - La oportunidad',title:'Que propone ENKI',summary:'ENKI es el respaldo productivo, digital y tecnico para vender mobiliario sin operar como fabrica.',message:'ENKI no sustituye al arquitecto frente al cliente. Lo acompana por detras para volver su propuesta fabricable.',deliverable:'Propuesta de valor base',tools:['Argumentario ENKI','Beneficios por etapa','Frase comercial corta'],prompt:'Redacta una propuesta de valor para arquitectos: ENKI acompana como sistema de cotizacion, diseno tecnico, fabricacion, entrega y garantia. El cliente final sigue siendo atendido por el arquitecto.'},
{id:'linea-propia',part:'Parte 1 - La oportunidad',title:'Por que esto permite crear una linea propia',summary:'Al repetir soluciones, acabados y modulos, el arquitecto transforma proyectos aislados en una oferta escalable.',message:'El arquitecto construye marca. ENKI construye el producto.',deliverable:'Tesis estrategica de linea propia',tools:['Lenguaje visual','Catalogo base','Paquetes repetibles'],prompt:'Explica como un arquitecto puede transformar proyectos de mobiliario a medida en una linea propia con catalogo base, acabados, modulos, paquetes, estilo reconocible y respaldo industrial ENKI.'},
{id:'quien-atiende',part:'Parte 2 - Modelo operativo',title:'Quien atiende a quien',summary:'El cliente final es atendido por el arquitecto. ENKI atiende al arquitecto como back office productivo.',message:'ENKI es el back office productivo del arquitecto. No compite con el. Lo potencia.',deliverable:'Regla de relacion comercial',tools:['Guion de roles','Politica de comunicacion','Limites de soporte'],prompt:'Define con claridad los roles de cliente final, arquitecto y ENKI. El cliente final es atendido por el arquitecto; ENKI atiende al arquitecto en estimaciones, diseno tecnico, cotizacion, fabricacion, entrega, instalacion y garantia.'},
{id:'roles',part:'Parte 2 - Modelo operativo',title:'Roles y responsabilidades',summary:'Cada actor debe saber que decide, que entrega, que aprueba y que no debe asumir.',message:'Un proyecto escala mejor cuando las responsabilidades estan documentadas antes de producir.',deliverable:'Matriz de responsabilidades',tools:['Matriz Arquitecto / ENKI / Cliente / Proveedores','Lista de aprobaciones','Limites de garantia'],prompt:'Crea una matriz de responsabilidades para un proyecto de mobiliario con ENKI. Incluye arquitecto, ENKI, cliente final y proveedores externos.'},
{id:'flujo-simple',part:'Parte 2 - Modelo operativo',title:'Flujo simple del proyecto',summary:'El flujo arranca con captacion, preguntas clave, estimado general y moodboard pagado antes del levantamiento.',message:'Primero se valida rango, estilo e intencion. Luego se mide, disena, cotiza y fabrica.',deliverable:'Mapa de proceso de 14 fases',tools:['Tabla por fase','Checklist de avance','Puntos de aprobacion'],prompt:'Convierte el flujo ENKI en un proceso comercial simple: captacion, preguntas, estimado, moodboard pagado, aprobacion, levantamiento, diseno, cotizacion, cierre, freeze, produccion, entrega e instalacion y garantia.'},
{id:'preguntas',part:'Parte 2 - Modelo operativo',title:'5 preguntas clave',summary:'Cinco preguntas iniciales ordenan espacio, necesidad, referencias, presupuesto y urgencia.',message:'La salida de las 5 preguntas no es cotizacion formal: es la base para un estimado general.',deliverable:'Brief inicial de captacion',tools:['Formulario breve','Guion de llamada','Criterios para clasificar lead'],prompt:'Arma un brief inicial con estas 5 preguntas: que espacio quiere intervenir, que necesita resolver, que referencias visuales le gustan, cual es su presupuesto y para cuando lo necesita.'},
{id:'estimado',part:'Parte 2 - Modelo operativo',title:'Estimado general inicial',summary:'Antes del moodboard se entrega una aproximacion basada en espacio, tamano, acabados, urgencia y complejidad.',message:'El estimado ordena expectativas y permite cobrar el moodboard sin regalar trabajo creativo.',deliverable:'Rango inicial de costo',tools:['Formato no vinculante','Rangos por espacio','Notas de alcance'],prompt:'Genera un estimado general inicial para mobiliario. Aclara que no es precio final, no es cotizacion cerrada y no compromete fabricacion.'},
{id:'moodboard',part:'Parte 2 - Modelo operativo',title:'Moodboard pagado',summary:'El moodboard es el primer servicio profesional pagado: direccion estetica y conceptual antes de levantamiento.',message:'Si el proyecto se estima en Ref. 10.000, el moodboard recomendado es Ref. 100.',deliverable:'Moodboard aprobado o descartado',tools:['Calculadora 1%','Prompt ENKI moodboard','Guia de datos'],prompt:'Crea una presentacion tipo moodboard estilo ENKI: limpia, sobria, premium, tecnica y editorial. Incluye concepto, imagen principal, referencias, paleta de materiales, acabados, criterios tecnicos y notas comerciales.'},
{id:'levantamiento',part:'Parte 2 - Modelo operativo',title:'Levantamiento',summary:'Solo se avanza al levantamiento si el cliente acepta continuar despues del moodboard.',message:'El levantamiento convierte una intencion comercial en una base real para disenar y cotizar.',deliverable:'Medidas, fotos, videos y condiciones tecnicas',tools:['Checklist de medicion','Registro fotografico','Mapa de riesgos'],prompt:'Crea una checklist de levantamiento: medidas, fotos, videos, puntos tecnicos, condiciones de obra, accesos, riesgos e instalaciones existentes.'},
{id:'diseno-plataforma',part:'Parte 3 - Diseno y cotizacion',title:'Diseno con plataforma ENKI o plugin SketchUp',summary:'El diseno debe verse bien y tambien poder cotizarse, fabricarse, documentarse, entregarse y garantizarse.',message:'Disenar dentro del sistema reduce improvisacion y acelera la traduccion a produccion.',deliverable:'Diseno digital fabricable',tools:['Biblioteca de modulos','Configurador de acabados','Restricciones productivas'],prompt:'Convierte una idea de mobiliario en un diseno digital fabricable para ENKI, considerando modulos, medidas, acabados, herrajes, restricciones tecnicas e instalacion.'},
{id:'cotizacion-formal',part:'Parte 3 - Diseno y cotizacion',title:'Cotizacion formal',summary:'Luego del diseno tecnico, ENKI entrega una cotizacion real al arquitecto.',message:'La cotizacion formal llega despues del levantamiento y del diseno fabricable.',deliverable:'Precio real para cierre comercial',tools:['Formato de cotizacion','Condiciones y exclusiones','Resumen para cliente'],prompt:'Estructura una cotizacion formal con materiales, herrajes, modulos, fabricacion, transporte, instalacion si aplica, tiempos, condiciones, exclusiones y validez.'},
{id:'presentacion-diseno',part:'Parte 3 - Diseno y cotizacion',title:'Presentacion de Diseno',summary:'Una presentacion ordenada ayuda al cliente a entender propuesta, estetica, funcionalidad y alcance.',message:'El diseno se vende mejor cuando se muestra como decision, no como acumulacion de imagenes.',deliverable:'Presentacion comercial de diseno',tools:['Estructura de laminas','Resumen conceptual','Comparativo de opciones'],prompt:'Crea una presentacion de diseno para vender un proyecto de mobiliario. Organiza concepto, necesidades resueltas, distribucion, materiales, referencias, criterios tecnicos y decisiones pendientes.'},
{id:'presentacion-ejecucion',part:'Parte 3 - Diseno y cotizacion',title:'Presentacion de Ejecucion',summary:'Transforma una propuesta aprobada en instrucciones claras para producir, instalar y coordinar.',message:'Una buena ejecucion empieza cuando el alcance queda documentado antes de fabrica.',deliverable:'Documento tecnico de ejecucion',tools:['Planos y elevaciones','Lista de materiales','Coordinacion de especialidades'],prompt:'Arma una presentacion de ejecucion con medidas finales, elevaciones, materiales, herrajes, detalles tecnicos, puntos de instalacion, exclusiones y pendientes.'},
{id:'freeze',part:'Parte 3 - Diseno y cotizacion',title:'Freeze y pedido',summary:'El freeze congela diseno, materiales, medidas y alcance antes de activar produccion.',message:'Despues del freeze, cualquier cambio debe documentarse y puede generar nueva cotizacion.',deliverable:'Diseno congelado y pedido activado',tools:['Checklist final','Registro de cambios','Confirmacion de anticipo'],prompt:'Crea un protocolo de freeze: medidas, diseno, materiales, herrajes, colores, cantidades, instalacion, condiciones comerciales, anticipo y manejo de cambios.'},
{id:'fabricacion',part:'Parte 4 - Produccion ENKI',title:'Fabricacion',summary:'ENKI convierte el diseno aprobado en despiece, corte, mecanizado, canteo, calidad, etiquetado y embalaje.',message:'El respaldo industrial reduce error, mejora trazabilidad y permite escalar.',deliverable:'Mobiliario fabricado con estandar industrial',tools:['Despiece','Lista de corte','Control de calidad'],prompt:'Explica el proceso de fabricacion industrial ENKI: despiece, corte, mecanizado, canteo, control de calidad, etiquetado, embalaje y entrega.'},
{id:'proveedores',part:'Parte 4 - Produccion ENKI',title:'Proveedores y acabados',summary:'ENKI conecta el diseno con disponibilidad real de tableros, laminados, herrajes, iluminacion y accesorios.',message:'La seleccion de acabados debe ser deseable, disponible, cotizable y fabricable.',deliverable:'Propuesta aterrizada al mercado local',tools:['Biblioteca de proveedores','Matriz de acabados','Alternativas por presupuesto'],prompt:'Construye una propuesta de acabados con disponibilidad local: tableros, laminados, herrajes, LED, tiradores, bisagras, correderas y accesorios.'},
{id:'entrega-instalacion',part:'Parte 4 - Produccion ENKI',title:'Entrega e instalacion',summary:'ENKI puede encargarse de entrega, instalacion, ajustes finales, revision funcional y acta de entrega.',message:'El arquitecto coordina el proyecto completo; ENKI responde por su alcance de carpinteria.',deliverable:'Producto de carpinteria entregado funcionalmente',tools:['Checklist de instalacion','Acta de entrega','Lista de pendientes'],prompt:'Crea una checklist de entrega e instalacion: transporte, acceso, piezas, instalacion, ajustes, pruebas funcionales, fotos, acta y responsabilidades.'},
{id:'garantia',part:'Parte 4 - Produccion ENKI',title:'Garantia',summary:'La garantia cubre fabricacion, herrajes segun proveedor, ajustes de instalacion y reposiciones cuando correspondan.',message:'Una garantia clara protege al cliente, al arquitecto y a ENKI.',deliverable:'Politica de garantia defendible',tools:['Cobertura','Exclusiones','Protocolo postventa'],prompt:'Redacta una politica de garantia para mobiliario ENKI: que cubre, que no cubre, como se reporta, tiempos, trazabilidad y exclusiones.'},
{id:'servicios-digitales',part:'Parte 5 - Negocio para el arquitecto',title:'Menu de servicios digitales',summary:'El sistema se organiza en diagnostico, direccion visual, diseno, ejecucion y cambios.',message:'El arquitecto puede vender etapas, no regalar todo el proceso desde la primera conversacion.',deliverable:'Menu comercial de servicios',tools:['Niveles de servicio','Entregables por nivel','Reglas de cobro'],prompt:'Organiza un menu de servicios digitales para arquitectos que venden mobiliario con ENKI: diagnostico, direccion visual, diseno, ejecucion y cambios.'},
{id:'tarifario',part:'Parte 5 - Negocio para el arquitecto',title:'Tarifario',summary:'El tarifario vuelve cobrables moodboard, cotizacion con diseno, presentaciones, cambios y pedido.',message:'El objetivo del tarifario es evitar trabajo gratis y ordenar expectativas desde el principio.',deliverable:'Tabla de precios y reglas de cobro',tools:['Moodboard al 1%','Presentaciones USD 30 / espacio / dia','Cambios por hora o ronda'],prompt:'Estructura un tarifario de servicios digitales: estimado, moodboard 1%, cotizacion, presentacion de diseno, presentacion de ejecucion, cambios y pedido.'},
{id:'modelo-economico',part:'Parte 5 - Negocio para el arquitecto',title:'Como gana dinero el arquitecto',summary:'El arquitecto puede cobrar servicios iniciales, ganar margen sobre mobiliario, presentar precio final y convertir diseno en producto vendible.',message:'El mobiliario deja de ser un problema de coordinacion y se convierte en una linea de ingreso.',deliverable:'Modelo economico para el arquitecto',tools:['Mapa de ingresos','Politica de margen','Guion de precio final','Calculadora mensual de rentabilidad'],prompt:'Explica como gana dinero el arquitecto usando ENKI: moodboard, diseno, margen sobre mobiliario, margen llave en mano, precio final, cambios y linea propia. Luego arma una lectura mensual con proyectos, tableros, costos, utilidad y punto de equilibrio.'},
{id:'casos-uso',part:'Parte 5 - Negocio para el arquitecto',title:'Casos de uso',summary:'Los casos concretos ayudan a vender: cocina, cuarto infantil, apartamento completo, closets y muebles personalizados.',message:'El modelo se entiende mas rapido cuando se ve aplicado a proyectos reales.',deliverable:'Biblioteca inicial de casos',tools:['Cocina','Cuarto infantil','Apartamento completo','Linea de closets','Mueble personalizado'],prompt:'Desarrolla 5 casos de uso para vender ENKI a arquitectos: cocina, cuarto infantil, apartamento completo, linea de closets y muebles estandar personalizados.'},
{id:'escalabilidad',part:'Parte 5 - Negocio para el arquitecto',title:'Escalabilidad',summary:'El arquitecto puede crecer desde proyectos puntuales hasta operar como marca de mobiliario con respaldo ENKI.',message:'La escala aparece cuando el arquitecto repite, documenta, empaqueta y vende mejor sus soluciones.',deliverable:'Ruta de crecimiento',tools:['Nivel basico','Nivel intermedio','Nivel avanzado','Nivel premium'],prompt:'Crea una ruta de escalabilidad para un arquitecto que usa ENKI: basico, intermedio, avanzado y premium. Explica oferta, procesos, margen, catalogo, marca y operacion.'},
{id:'evitar',part:'Parte 5 - Negocio para el arquitecto',title:'Que debe evitar el arquitecto',summary:'El modelo se protege evitando promesas sin validar, cotizaciones prematuras y responsabilidades mezcladas.',message:'La claridad comercial tambien es una herramienta de diseno.',deliverable:'Lista de riesgos y reglas de proteccion',tools:['No hablar de precio final antes de tiempo','No disenar fuera del sistema','No asumir errores externos'],prompt:'Crea una lista de errores que debe evitar un arquitecto al vender mobiliario con ENKI y agrega recomendaciones practicas.'}
];

const flow=[['1. Captacion','Arquitecto / Asesor','Lead inicial','10-20 min'],['2. 5 preguntas clave','Arquitecto / Asesor','Informacion base','10-15 min'],['3. Estimado general','Arquitecto + ENKI si aplica','Rango de costo','24-48 h'],['4. Cobro moodboard','Arquitecto','Pago 1%','1 dia'],['5. Moodboard','Arquitecto / Disenador','Direccion estetica','1-3 dias'],['6. Aprobacion cliente','Arquitecto','Avance a fase 2','1 dia'],['7. Levantamiento','Arquitecto / Tecnico','Medidas + fotos','1-2 h'],['8. Diseno digital','Arquitecto + ENKI','Diseno fabricable','2-5 dias'],['9. Cotizacion formal','ENKI -> Arquitecto','Precio real','24-72 h'],['10. Cierre','Arquitecto','Anticipo + aprobacion','1 dia'],['11. Freeze','Arquitecto + ENKI','Diseno congelado','24-48 h'],['12. Produccion','ENKI','Carpinteria fabricada','3-5 semanas'],['13. Entrega / instalacion','ENKI','Mueble funcional','1-3 dias'],['14. Garantia','ENKI','Respaldo postventa','Segun caso']];
let activeBlockId=blocks[0].id;
const $=s=>document.querySelector(s);
const blockList=$('#blockList'),selectedBlock=$('#selectedBlock'),searchInput=$('#searchInput'),estimateInput=$('#estimateInput'),moodboardFee=$('#moodboardFee'),flowTable=$('#flowTable'),generatedPrompt=$('#generatedPrompt'),copyNotice=$('#copyNotice');
const fields=['projectName','clientName','spaceType','styleIntent'].map(id=>$(`#${id}`));
const profitInputs=['projectsPerMonth','boardsPerProject','boardSellPrice','boardCost','turnkeyCostPerProject','turnkeyMarkup','designFeePerProject','monthlyFixedCosts','moodboardsPerMonth','moodboardAverageProject'].map(id=>$(`#${id}`)).filter(Boolean);
const profitOutputs=['netProfit','profitReadout','totalMonthlyRevenue','netMargin','grossProfit','totalDirectCosts','boardsPerMonth','capacityUse','breakEvenProjects','profitPerBoard','carpentryGrossProfit','turnkeyGrossProfit','serviceRevenue'].reduce((a,id)=>({...a,[id]:$(`#${id}`)}),{});
function visibleBlocks(){const q=(searchInput?.value||'').trim().toLowerCase();return q?blocks.filter(b=>[b.title,b.part,b.summary,b.message,b.deliverable,b.prompt,...b.tools].join(' ').toLowerCase().includes(q)):blocks;}
function renderBlockList(items=visibleBlocks()){blockList.innerHTML='';items.forEach(b=>{const btn=document.createElement('button');btn.type='button';btn.className=`nav-button ${b.id===activeBlockId?'active':''}`;btn.innerHTML=`<span class='block-part'>${b.part}</span><strong>${blocks.indexOf(b)+1}. ${b.title}</strong>`;btn.addEventListener('click',()=>{activeBlockId=b.id;render();selectedBlock.scrollIntoView({behavior:'smooth',block:'start'});});blockList.appendChild(btn);});}
function renderSelectedBlock(){const b=blocks.find(x=>x.id===activeBlockId)||blocks[0];selectedBlock.innerHTML=`<header class='block-header'><p class='eyebrow'>${b.part}</p><h2>${b.title}</h2><p class='block-summary'>${b.summary}</p></header><div class='message-box'><strong>Mensaje clave:</strong> ${b.message}</div><div class='detail-grid'><article class='detail-panel'><h3>Herramientas del bloque</h3><ul>${b.tools.map(t=>`<li>${t}</li>`).join('')}</ul></article><article class='detail-panel'><h3>Entregable esperado</h3><p>${b.deliverable}</p></article></div>`;}
function renderFlow(){flowTable.innerHTML=flow.map(([p,o,d,t])=>`<div class='flow-row'><strong>${p}</strong><span>${o}</span><span>${d}</span><span class='flow-time'>${t}</span></div>`).join('');}
function updateCalculator(){const fee=Number(estimateInput.value||0)*0.01;moodboardFee.textContent=`Ref. ${fee.toLocaleString('en-US',{maximumFractionDigits:2})}`;}
function num(id){return Number($(`#${id}`)?.value||0);}
function money(v,d=0){const sign=v<0?'-':'';return `${sign}Ref. ${Math.abs(v).toLocaleString('en-US',{maximumFractionDigits:d})}`;}
function pct(v){return `${v.toLocaleString('en-US',{maximumFractionDigits:1})}%`;}
function out(k,v){if(profitOutputs[k])profitOutputs[k].textContent=v;}
function updateProfitCalculator(){if(!profitOutputs.netProfit)return;const projects=num('projectsPerMonth'),bpp=num('boardsPerProject'),sell=num('boardSellPrice'),cost=num('boardCost'),ext=num('turnkeyCostPerProject'),mk=num('turnkeyMarkup')/100,fee=num('designFeePerProject'),fixed=num('monthlyFixedCosts'),moods=num('moodboardsPerMonth'),avg=num('moodboardAverageProject');const boards=projects*bpp,carpRev=boards*sell,carpCost=boards*cost,carpGP=carpRev-carpCost,turnCost=projects*ext,turnRev=turnCost*(1+mk),turnGP=turnRev-turnCost,moodRev=moods*avg*0.01,designRev=projects*fee,serviceRev=moodRev+designRev,totalRev=carpRev+turnRev+serviceRev,direct=carpCost+turnCost,gross=totalRev-direct,net=gross-fixed,margin=totalRev?net/totalRev*100:0,profitBoard=sell-cost,capacity=boards/1000*100,contrib=bpp*profitBoard+ext*mk+fee,be=contrib>0?Math.ceil(Math.max(0,fixed-moodRev)/contrib):0;out('netProfit',money(net));out('totalMonthlyRevenue',money(totalRev));out('netMargin',pct(margin));out('grossProfit',money(gross));out('totalDirectCosts',money(direct));out('boardsPerMonth',boards.toLocaleString('en-US',{maximumFractionDigits:0}));out('capacityUse',pct(capacity));out('breakEvenProjects',`${be} proyectos`);out('profitPerBoard',money(profitBoard));out('carpentryGrossProfit',money(carpGP));out('turnkeyGrossProfit',money(turnGP));out('serviceRevenue',money(serviceRev));profitOutputs.netProfit.closest('.metric-main')?.classList.toggle('loss',net<0);profitOutputs.profitReadout.textContent=net>=0?`Con ${projects} proyectos/mes y ${boards.toLocaleString('en-US')} tableros, la operacion deja ${money(net)} netos despues de gastos fijos. Cada proyecto aporta aprox. ${money(contrib)} antes de gastos fijos.`:`Con este escenario faltan ${money(Math.abs(net))} para cubrir gastos fijos mensuales. Cada proyecto aporta aprox. ${money(contrib)} antes de gastos fijos.`;}
function buildPrompt(){const b=blocks.find(x=>x.id===activeBlockId)||blocks[0];const [project,client,space,style]=fields.map(f=>f.value.trim());generatedPrompt.value=`${b.prompt}\n\nContexto del proyecto:\n- Proyecto: ${project||'[Nombre del proyecto]'}\n- Cliente: ${client||'[Nombre del cliente]'}\n- Espacio: ${space||'[Tipo de espacio]'}\n- Estilo / intencion: ${style||'[Palabras clave del estilo]'}\n\nQuiero que la salida sea clara, vendible y accionable para un arquitecto. Mantener el enfoque correcto: el arquitecto atiende y lidera al cliente final; ENKI acompana al arquitecto como respaldo tecnico, digital y productivo.`;}
async function copyText(text){try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);else throw new Error('Clipboard API unavailable');}catch(e){const helper=document.createElement('textarea');helper.value=text;helper.setAttribute('readonly','');helper.style.position='fixed';helper.style.left='-9999px';document.body.appendChild(helper);helper.select();document.execCommand('copy');document.body.removeChild(helper);}copyNotice.textContent='Prompt copiado.';window.setTimeout(()=>{copyNotice.textContent='';},1800);}
function render(){renderBlockList(visibleBlocks());renderSelectedBlock();renderFlow();updateCalculator();updateProfitCalculator();buildPrompt();}
searchInput.addEventListener('input',()=>renderBlockList(visibleBlocks()));estimateInput.addEventListener('input',updateCalculator);profitInputs.forEach(i=>i.addEventListener('input',updateProfitCalculator));fields.forEach(f=>f.addEventListener('input',buildPrompt));$('#copyCurrentPrompt').addEventListener('click',()=>copyText(generatedPrompt.value));$('#copyGeneratedPrompt').addEventListener('click',()=>copyText(generatedPrompt.value));$('#openProfit').addEventListener('click',()=>{activeBlockId='modelo-economico';render();$('#profitCalculator').scrollIntoView({behavior:'smooth',block:'start'});});$('#openFlow').addEventListener('click',()=>{$('#flowPanel').scrollIntoView({behavior:'smooth',block:'start'});});
render();
